// shatter-words.js v1.0.0 — GENERATED. Round 102 (Pittsburg).
//
// ⚠️ DO NOT HAND-EDIT. Rebuild: build-word-banks.py, then a model pass
// (shatter-gemini-prompt.md), then rejoin-shatter.py.
//
// Each entry: w = word, p = morphemes in order (they concatenate back to
// w — verified, not assumed), lemma = the dictionary form where English
// dropped a silent e (debating: p is debat+ing, lemma is debate+ing — the
// tiles rebuild the word, the hover explains the spelling change),
// g = a plain-English gloss per part for the
// pause-and-hover, books = where it appears in the TTB library.

export const SHATTER_WORDS = [
    { w: 'abandoned', p: ['abandon','ed'], g: ['to leave behind','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Tower Treasure','Short Fiction'], n: 30 },
    { w: 'abruptly', p: ['abrupt','ly'], g: ['sudden or unexpected','in a way that is'], grade: 'easy', books: ['Pollyanna','The War of the Worlds','Daughters of the Dominion: A Story of the Canadian Frontier'], n: 44 },
    { w: 'absently', p: ['absent','ly'], g: ['not present or distracted','in a way that is'], grade: 'easy', books: ['Little Women','Jeeves Stories','The Story of the Amulet'], n: 16 },
    { w: 'absolutely', p: ['absolute','ly'], g: ['complete or total','in a way that is'], grade: 'easy', books: ['Jeeves Stories','The Adventures of Sherlock Holmes','Jane Eyre'], n: 48 },
    { w: 'accents', p: ['accent','s'], g: ['pronunciation or emphasis','plural'], grade: 'easy', books: ['Jane Eyre','Frankenstein','The Count of Monte Cristo'], n: 14 },
    { w: 'acceptable', p: ['accept','able'], g: ['to receive or agree to','able to be'], grade: 'easy', books: ['Pride and Prejudice','The Count of Monte Cristo','Jane Eyre'], n: 12 },
    { w: 'accepted', p: ['accept','ed'], g: ['to receive or agree to','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','White Fang'], n: 55 },
    { w: 'accepting', p: ['accept','ing'], g: ['to receive or agree to','doing action'], grade: 'easy', books: ['Pride and Prejudice','The Count of Monte Cristo','Dracula'], n: 25 },
    { w: 'accidental', p: ['accident','al'], g: ['unintended event','relating to'], grade: 'easy', books: ['Pride and Prejudice','Fables','Northanger Abbey'], n: 18 },
    { w: 'accidentally', p: ['accidental','ly'], g: ['unintended or by chance','in a way that is'], grade: 'easy', books: ['The Count of Monte Cristo','The Tower Treasure','Northanger Abbey'], n: 22 },
    { w: 'accidents', p: ['accident','s'], g: ['unintended events','plural'], grade: 'easy', books: ['Frankenstein','Daughters of the Dominion: A Story of the Canadian Frontier','Little Women'], n: 23 },
    { w: 'accompanying', p: ['accompany','ing'], g: ['to go along with','doing action'], grade: 'medium', books: ['The Count of Monte Cristo','Northanger Abbey','Jane Eyre'], n: 20 },
    { w: 'accomplished', p: ['accomplish','ed'], g: ['to complete or achieve','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Pride and Prejudice','Little Women'], n: 47 },
    { w: 'accomplishment', p: ['accomplish','ment'], g: ['to complete or achieve','action or result'], grade: 'medium', books: ['The Count of Monte Cristo','Pride and Prejudice','Daughters of the Dominion: A Story of the Canadian Frontier'], n: 21 },
    { w: 'accomplishments', p: ['accomplishment','s'], g: ['completed achievements','plural'], grade: 'medium', books: ['Jane Eyre','Little Women','Pride and Prejudice'], n: 11 },
    { w: 'accorded', p: ['accord','ed'], g: ['to grant or agree','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Jane Eyre','Frankenstein'], n: 12 },
    { w: 'according', p: ['accord','ing'], g: ['to agree or match','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Journey to the Center of the Earth'], n: 51 },
    { w: 'accordingly', p: ['according','ly'], g: ['in agreement or conformity','in a way that is'], grade: 'medium', books: ['Indian Fairy Tales','Frankenstein','Jane Eyre'], n: 33 },
    { w: 'accounted', p: ['account','ed'], g: ['to explain or reckon','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Northanger Abbey','Pride and Prejudice'], n: 28 },
    { w: 'accounts', p: ['account','s'], g: ['reports or records','plural'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Jane Eyre'], n: 41 },
    { w: 'accurately', p: ['accurate','ly'], g: ['correct or precise','in a way that is'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Dracula'], n: 13 },
    { w: 'acquaintances', p: ['acquaintance','s'], g: ['people known slightly','plural'], grade: 'medium', books: ['The Count of Monte Cristo','Short Fiction','Little Lord Fauntleroy'], n: 26 },
    { w: 'acres', p: ['acre','s'], g: ['units of land area','plural'], grade: 'easy', books: ['Short Fiction','A Girl of the Limberlost','The Count of Monte Cristo'], n: 21 },
    { w: 'acted', p: ['act','ed'], g: ['to do or perform','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','The Adventures of Sherlock Holmes'], n: 38 },
    { w: 'acting', p: ['act','ing'], g: ['to do or perform','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Grace Harlowe\'s Plebe Year at High School / The Merry Doings of the Oakdale Freshmen Girls','Jane Eyre'], n: 39 },
    { w: 'actions', p: ['action','s'], g: ['deeds or movements','plural'], grade: 'easy', books: ['The Count of Monte Cristo','The Girls of Central High at Basketball','White Fang'], n: 38 },
    { w: 'active', p: ['act','ive'], g: ['to do or perform','having the quality of'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Short Fiction'], n: 45 },
    { w: 'actors', p: ['actor','s'], g: ['people who perform','plural'], grade: 'easy', books: ['The Count of Monte Cristo','Grace Harlowe\'s Plebe Year at High School / The Merry Doings of the Oakdale Freshmen Girls','Short Fiction'], n: 9 },
    { w: 'actually', p: ['actual','ly'], g: ['real or existing','in a way that is'], grade: 'easy', books: ['A Little Princess','Little Lord Fauntleroy','Little Women'], n: 59 },
    { w: 'added', p: ['add','ed'], g: ['to join or combine','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Pride and Prejudice'], n: 71 },
    { w: 'adding', p: ['add','ing'], g: ['to join or combine','doing action'], grade: 'easy', books: ['Little Women','The Count of Monte Cristo','Jane Eyre'], n: 38 },
    { w: 'additional', p: ['addition','al'], g: ['something added','relating to'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','The Secret of the Old Clock'], n: 24 },
    { w: 'addressed', p: ['address','ed'], g: ['to speak to or direct toward','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Pride and Prejudice'], n: 53 },
    { w: 'addressing', p: ['address','ing'], g: ['to speak to or direct toward','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Short Fiction'], n: 34 },
    { w: 'admiringly', p: ['admiring','ly'], g: ['looking at with pleasure','in a way that is'], grade: 'easy', books: ['The Box-Car Children','Anne of Green Gables','The Girl Aviators and the Phantom Airship'], n: 18 },
    { w: 'adopted', p: ['adopt','ed'], g: ['to take as one\'s own','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','A Little Princess','Jane Eyre'], n: 29 },
    { w: 'advances', p: ['advance','s'], g: ['to move forward','plural / present tense'], grade: 'easy', books: ['The Call of the Wild','Northanger Abbey','Jane Eyre'], n: 17 },
    { w: 'advantages', p: ['advantage','s'], g: ['helpful conditions or benefits','plural'], grade: 'easy', books: ['Pride and Prejudice','The Count of Monte Cristo','Rebecca of Sunnybrook Farm'], n: 26 },
    { w: 'adventures', p: ['adventure','s'], g: ['exciting experiences','plural'], grade: 'easy', books: ['The Wind in the Willows','The Lost World','The Magic City'], n: 54 },
    { w: 'advertisement', p: ['advertise','ment'], g: ['to promote or announce','result or notice'], grade: 'easy', books: ['The Adventures of Sherlock Holmes','The Story of the Treasure Seekers','Short Fiction'], n: 19 },
    { w: 'advertisements', p: ['advertisement','s'], g: ['notices promoting things','plural'], grade: 'easy', books: ['Jeeves Stories','Jane Eyre','The Story of the Treasure Seekers'], n: 11 },
    { w: 'affairs', p: ['affair','s'], g: ['matters or events','plural'], grade: 'easy', books: ['The Count of Monte Cristo','Dracula','Little Women'], n: 52 },
    { w: 'affected', p: ['affect','ed'], g: ['to influence or change','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Little Women'], n: 38 },
    { w: 'affecting', p: ['affect','ing'], g: ['to influence or change','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Anne of Green Gables','Jeeves Stories'], n: 11 },
    { w: 'affectionately', p: ['affectionate','ly'], g: ['showing fondness or love','in a way that is'], grade: 'easy', books: ['Daddy Long-Legs','The Count of Monte Cristo','Pride and Prejudice'], n: 31 },
    { w: 'affections', p: ['affection','s'], g: ['feelings of love or fondness','plural'], grade: 'easy', books: ['Frankenstein','The Count of Monte Cristo','Little Women'], n: 18 },
    { w: 'afforded', p: ['afford','ed'], g: ['to provide or be able to pay','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','Pride and Prejudice'], n: 26 },
    { w: 'afternoons', p: ['afternoon','s'], g: ['times between noon and evening','plural'], grade: 'easy', books: ['Anne of Green Gables','Little Women','Barry Locke, half-back'], n: 23 },
    { w: 'afterward', p: ['after','ward'], g: ['following in time','direction toward'], grade: 'easy', books: ['Short Fiction','The Golden Fleece and The Heroes Who Lived Before Achilles','Little Women'], n: 38 },
    { w: 'afterwards', p: ['afterward','s'], g: ['at a later time','adverbial suffix'], grade: 'easy', books: ['The Count of Monte Cristo','The Story of the Treasure Seekers','Pride and Prejudice'], n: 52 },
    { w: 'agents', p: ['agent','s'], g: ['representatives or actors','plural'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Dracula'], n: 9 },
    { w: 'agreeable', p: ['agree','able'], g: ['to concur or match','able to be / pleasant'], grade: 'easy', books: ['Pride and Prejudice','Northanger Abbey','The Count of Monte Cristo'], n: 38 },
    { w: 'agreement', p: ['agree','ment'], g: ['to concur or match','result or arrangement'], grade: 'easy', books: ['The Count of Monte Cristo','Celtic Fairy Tales','Fables'], n: 22 },
    { w: 'aided', p: ['aid','ed'], g: ['to help or assist','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','The Girl Aviators and the Phantom Airship'], n: 19 },
    { w: 'aimed', p: ['aim','ed'], g: ['to point or direct','past tense'], grade: 'easy', books: ['The High School Left End','The Adventures of Odysseus and The Tales of Troy','The Count of Monte Cristo'], n: 19 },
    { w: 'alarmed', p: ['alarm','ed'], g: ['frightened or warned','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Circular Staircase','A Little Princess'], n: 39 },
    { w: 'alarming', p: ['alarm','ing'], g: ['frightening or warning','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Northanger Abbey','Pride and Prejudice'], n: 29 },
    { w: 'alighted', p: ['alight','ed'], g: ['to land or step down','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','The Girl Aviators and the Phantom Airship','Jane Eyre'], n: 28 },
    { w: 'allowed', p: ['allow','ed'], g: ['to permit or let','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Short Fiction'], n: 66 },
    { w: 'allowing', p: ['allow','ing'], g: ['to permit or let','doing action'], grade: 'easy', books: ['Pride and Prejudice','The Count of Monte Cristo','Jeeves Stories'], n: 22 },
    { w: 'allows', p: ['allow','s'], g: ['to permit or let','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','The Adventures of Sherlock Holmes'], n: 15 },
    { w: 'altered', p: ['alter','ed'], g: ['to change or adjust','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Jane Eyre'], n: 35 },
    { w: 'amazingly', p: ['amazing','ly'], g: ['causing wonder or surprise','in a way that is'], grade: 'easy', books: ['Northanger Abbey','Little Women','Daughters of the Dominion: A Story of the Canadian Frontier'], n: 14 },
    { w: 'ambitions', p: ['ambition','s'], g: ['strong desires or goals','plural'], grade: 'easy', books: ['Short Fiction','Anne of Green Gables','A Girl of the Limberlost'], n: 14 },
    { w: 'amounted', p: ['amount','ed'], g: ['to add up to','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Short Fiction'], n: 15 },
    { w: 'amounts', p: ['amount','s'], g: ['totals or quantities','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Jeeves Stories'], n: 10 },
    { w: 'amusement', p: ['amuse','ment'], g: ['to entertain or delight','state or result'], grade: 'easy', books: ['Pride and Prejudice','Little Women','Short Fiction'], n: 44 },
    { w: 'amusements', p: ['amusement','s'], g: ['entertainments or games','plural'], grade: 'easy', books: ['The Magic City','Pride and Prejudice','The Count of Monte Cristo'], n: 20 },
    { w: 'angels', p: ['angel','s'], g: ['heavenly beings','plural'], grade: 'easy', books: ['At the Back of the North Wind','Little Women','Jane Eyre'], n: 22 },
    { w: 'angered', p: ['anger','ed'], g: ['strong displeasure','past tense'], grade: 'easy', books: ['The Adventures of Odysseus and The Tales of Troy','Black Beauty','The High School Left End'], n: 16 },
    { w: 'angles', p: ['angle','s'], g: ['corners or directions','plural'], grade: 'easy', books: ['The Count of Monte Cristo','White Fang','The Time Machine'], n: 15 },
    { w: 'animals', p: ['animal','s'], g: ['living creatures','plural'], grade: 'easy', books: ['The Wind in the Willows','White Fang','The Magic City'], n: 54 },
    { w: 'ankles', p: ['ankle','s'], g: ['joints above the feet','plural'], grade: 'easy', books: ['Short Fiction','At the Back of the North Wind','Pride and Prejudice'], n: 23 },
    { w: 'announcement', p: ['announce','ment'], g: ['to make known publicly','statement or act'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Barry Locke, half-back'], n: 22 },
    { w: 'annoyed', p: ['annoy','ed'], g: ['to bother or irritate','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Fables'], n: 39 },
    { w: 'annoying', p: ['annoy','ing'], g: ['to bother or irritate','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Three Men in a Boat','The Magic City'], n: 18 },
    { w: 'answered', p: ['answer','ed'], g: ['to reply or respond','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','At the Back of the North Wind','The Half-Back: A Story of School, Football, and Golf'], n: 77 },
    { w: 'answering', p: ['answer','ing'], g: ['to reply or respond','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Northanger Abbey'], n: 44 },
    { w: 'answers', p: ['answer','s'], g: ['replies or solutions','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Little Women'], n: 33 },
    { w: 'anxiously', p: ['anxious','ly'], g: ['worried or eager','in a way that is'], grade: 'easy', books: ['The Count of Monte Cristo','Alice’s Adventures in Wonderland','Daughters of the Dominion: A Story of the Canadian Frontier'], n: 56 },
    { w: 'apartment', p: ['apart','ment'], g: ['separate or set aside','place or result'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Jane Eyre'], n: 28 },
    { w: 'apartments', p: ['apartment','s'], g: ['sets of living rooms','plural'], grade: 'easy', books: ['The Count of Monte Cristo','Northanger Abbey','The Prisoner of Zenda'], n: 15 },
    { w: 'apparently', p: ['apparent','ly'], g: ['seeming or clear to see','in a way that is'], grade: 'medium', books: ['Jeeves Stories','The Count of Monte Cristo','The Girl from the Big Horn Country'], n: 51 },
    { w: 'appealed', p: ['appeal','ed'], g: ['to request earnestly or attract','past tense'], grade: 'easy', books: ['A Girl of the Limberlost','Jane Eyre','Rebecca of Sunnybrook Farm'], n: 27 },
    { w: 'appealing', p: ['appeal','ing'], g: ['to request earnestly or attract','doing action'], grade: 'easy', books: ['Dracula','A Little Princess','Little Women'], n: 15 },
    { w: 'appearances', p: ['appearance','s'], g: ['outward looks or comings','plural'], grade: 'easy', books: ['White Fang','Frankenstein','The Count of Monte Cristo'], n: 23 },
    { w: 'appeared', p: ['appear','ed'], g: ['to come into sight','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Frankenstein'], n: 75 },
    { w: 'appearing', p: ['appear','ing'], g: ['to come into sight','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Journey to the Center of the Earth'], n: 35 },
    { w: 'debating', p: ['debat','ing'], lemma: ['debate','ing'], g: ['to discuss or argue','doing action'], grade: 'easy', books: ['Anne of Green Gables','The Half-Back: A Story of School, Football, and Golf','The Half-Back: A Story of School, Football, and Golf'], n: 15 },
    { w: 'decently', p: ['decent','ly'], g: ['proper or respectable','in a way that is'], grade: 'easy', books: ['Jeeves Stories','The Count of Monte Cristo','Jane Eyre'], n: 18 },
    { w: 'declaration', p: ['declar','ation'], lemma: ['declare','ation'], g: ['to state clearly','action or result'], grade: 'medium', books: ['The Count of Monte Cristo','Understood Betsy','Pride and Prejudice'], n: 14 },
    { w: 'defeated', p: ['defeat','ed'], g: ['to win against','past tense'], grade: 'easy', books: ['The Half-Back: A Story of School, Football, and Golf','The Half-Back: A Story of School, Football, and Golf','The Count of Monte Cristo'], n: 23 },
    { w: 'defined', p: ['defin','ed'], lemma: ['define','ed'], g: ['to explain the meaning of','past tense'], grade: 'easy', books: ['The Lost World','The Count of Monte Cristo','Journey to the Center of the Earth'], n: 20 },
    { w: 'delayed', p: ['delay','ed'], g: ['to make late or slow down','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','White Fang'], n: 39 },
    { w: 'delighted', p: ['delight','ed'], g: ['great joy or pleasure','past tense / state of'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Little Women'], n: 65 },
    { w: 'delightful', p: ['delight','ful'], g: ['great joy or pleasure','full of'], grade: 'easy', books: ['Little Women','Northanger Abbey','The Count of Monte Cristo'], n: 52 },
    { w: 'delights', p: ['delight','s'], g: ['great joy or pleasure','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Short Fiction'], n: 19 },
    { w: 'delivered', p: ['deliver','ed'], g: ['to bring or hand over','past tense'], grade: 'easy', books: ['The Prince and the Pauper','The Count of Monte Cristo','Short Fiction'], n: 34 },
    { w: 'delivering', p: ['deliver','ing'], g: ['to bring or hand over','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','The Prince and the Pauper'], n: 14 },
    { w: 'delivery', p: ['deliver','y'], g: ['to bring or hand over','act or state of'], grade: 'easy', books: ['Short Fiction','Dracula','The Count of Monte Cristo'], n: 19 },
    { w: 'deserves', p: ['deserve','s'], g: ['to be worthy of','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Heidi'], n: 24 },
    { w: 'designed', p: ['design','ed'], g: ['to plan or draw','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','The Magic City'], n: 20 },
    { w: 'designs', p: ['design','s'], g: ['to plan or draw','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Northanger Abbey'], n: 13 },
    { w: 'desirable', p: ['desir','able'], lemma: ['desire','able'], g: ['to want or wish for','able to be'], grade: 'medium', books: ['Pride and Prejudice','Short Fiction','The Count of Monte Cristo'], n: 21 },
    { w: 'desired', p: ['desir','ed'], lemma: ['desire','ed'], g: ['to want or wish for','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','Jeeves Stories'], n: 51 },
    { w: 'desires', p: ['desire','s'], g: ['to want or wish for','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Frankenstein'], n: 29 },
    { w: 'desiring', p: ['desir','ing'], lemma: ['desire','ing'], g: ['to want or wish for','doing action'], grade: 'medium', books: ['The Count of Monte Cristo','Jane Eyre','Pride and Prejudice'], n: 13 },
    { w: 'desirous', p: ['desir','ous'], lemma: ['desire','ous'], g: ['to want or wish for','full of'], grade: 'hard', books: ['The Count of Monte Cristo','Pride and Prejudice','Jane Eyre'], n: 19 },
    { w: 'detailed', p: ['detail','ed'], g: ['a small part or feature','past tense / state of'], grade: 'easy', books: ['The Count of Monte Cristo','The Prince and the Pauper','The Adventures of Sherlock Holmes'], n: 14 },
    { w: 'details', p: ['detail','s'], g: ['small parts or features','plural'], grade: 'easy', books: ['The Count of Monte Cristo','The Adventures of Sherlock Holmes','Jane Eyre'], n: 36 },
    { w: 'detestable', p: ['detest','able'], g: ['to hate intensely','worthy of being'], grade: 'medium', books: ['The Count of Monte Cristo','The Strange Case of Dr. Jekyll and Mr. Hyde','A Little Princess'], n: 14 },
    { w: 'detested', p: ['detest','ed'], g: ['to hate intensely','past tense'], grade: 'easy', books: ['Frankenstein','The Count of Monte Cristo','The Chums of Scranton High at Ice Hockey'], n: 13 },
    { w: 'devices', p: ['device','s'], g: ['tools or gadgets','plural'], grade: 'easy', books: ['Little Women','The Prince and the Pauper','The Prisoner of Zenda'], n: 15 },
    { w: 'disgusted', p: ['disgust','ed'], g: ['strong dislike or revulsion','past tense / state of'], grade: 'easy', books: ['Fables','Little Women','Pride and Prejudice'], n: 22 },
    { w: 'dishonest', p: ['dis','honest'], g: ['not','truthful or fair'], grade: 'easy', books: ['Ruth Fielding of the Red Mill','The Camp Fire Girls in the Maine Woods','Fables'], n: 17 },
    { w: 'dismayed', p: ['dismay','ed'], g: ['distress or discouragement','past tense'], grade: 'medium', books: ['Daughters of the Dominion: A Story of the Canadian Frontier','Jane Eyre','At the Back of the North Wind'], n: 17 },
    { w: 'dismiss', p: ['dis','miss'], g: ['away / off','to send'], grade: 'easy', books: ['Jane Eyre','The Prince and the Pauper','The War of the Worlds'], n: 18 },
    { w: 'displayed', p: ['display','ed'], g: ['to show or exhibit','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Dracula','The Time Machine'], n: 42 },
    { w: 'displaying', p: ['display','ing'], g: ['to show or exhibit','doing action'], grade: 'easy', books: ['Little Women','Barry Locke, half-back','The Count of Monte Cristo'], n: 16 },
    { w: 'existed', p: ['exist','ed'], g: ['to be real or live','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Journey to the Center of the Earth','White Fang'], n: 24 },
    { w: 'existing', p: ['exist','ing'], g: ['to be real or live','doing action'], grade: 'easy', books: ['Frankenstein','Short Fiction','The Count of Monte Cristo'], n: 13 },
    { w: 'exists', p: ['exist','s'], g: ['to be real or live','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Lost World','Daddy Long-Legs'], n: 13 },
    { w: 'expensive', p: ['expens','ive'], lemma: ['expense','ive'], g: ['cost or price','having the quality of'], grade: 'easy', books: ['A Girl of the Limberlost','The Secret of the Old Clock','Short Fiction'], n: 34 },
    { w: 'images', p: ['image','s'], g: ['pictures or likenesses','plural'], grade: 'easy', books: ['The Story of the Amulet','Frankenstein','The Adventures of Odysseus and The Tales of Troy'], n: 13 },
    { w: 'improvement', p: ['improve','ment'], g: ['to make better','act or result of'], grade: 'easy', books: ['Pride and Prejudice','Jane Eyre','Northanger Abbey'], n: 29 },
    { w: 'incapable', p: ['in','capable'], g: ['not','able or skilled'], grade: 'easy', books: ['Jane Eyre','Pride and Prejudice','The Count of Monte Cristo'], n: 23 },
    { w: 'informed', p: ['inform','ed'], g: ['to tell or give news','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Pride and Prejudice'], n: 38 },
    { w: 'informing', p: ['inform','ing'], g: ['to tell or give news','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Pride and Prejudice'], n: 14 },
    { w: 'inhabited', p: ['inhabit','ed'], g: ['to live in or occupy','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Frankenstein','Journey to the Center of the Earth'], n: 16 },
    { w: 'intention', p: ['intent','ion'], g: ['aim or purpose','act or state of'], grade: 'medium', books: ['The Count of Monte Cristo','Pride and Prejudice','Jane Eyre'], n: 48 },
    { w: 'intently', p: ['intent','ly'], g: ['focused or purposeful','in a way that is'], grade: 'medium', books: ['A Girl of the Limberlost','The Count of Monte Cristo','Dracula'], n: 40 },
    { w: 'invented', p: ['invent','ed'], g: ['to create or discover','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Indian Fairy Tales','Short Fiction'], n: 30 },
    { w: 'presented', p: ['present','ed'], g: ['to show or give','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Frankenstein'], n: 54 },
    { w: 'presenting', p: ['present','ing'], g: ['to show or give','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','The Adventures of Pinocchio'], n: 14 },
    { w: 'presently', p: ['present','ly'], g: ['soon or currently','in a way that is'], grade: 'easy', books: ['The Prince and the Pauper','The Black Arrow: A Tale of the Two Roses','The Wind in the Willows'], n: 60 },
    { w: 'presents', p: ['present','s'], g: ['gifts or shows','plural / present tense'], grade: 'easy', books: ['The Story of the Treasure Seekers','Little Women','The Count of Monte Cristo'], n: 37 },
    { w: 'preserves', p: ['preserve','s'], g: ['to keep safe or save','plural / present tense'], grade: 'easy', books: ['Anne of Green Gables','A Girl of the Limberlost','The Count of Monte Cristo'], n: 10 },
    { w: 'pretended', p: ['pretend','ed'], g: ['to make believe','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Indian Fairy Tales','Peter and Wendy'], n: 42 },
    { w: 'pretending', p: ['pretend','ing'], g: ['to make believe','doing action'], grade: 'easy', books: ['A Little Princess','Daddy Long-Legs','Dracula'], n: 37 },
    { w: 'prevented', p: ['prevent','ed'], g: ['to stop from happening','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Northanger Abbey'], n: 39 },
    { w: 'reaches', p: ['reach','es'], g: ['to stretch to or arrive at','plural / present tense'], grade: 'easy', books: ['Indian Fairy Tales','Three Men in a Boat','A Girl of the Limberlost'], n: 18 },
    { w: 'really', p: ['real','ly'], g: ['true or actual','in a way that is'], grade: 'easy', books: ['The Count of Monte Cristo','Anne of Green Gables','Jeeves Stories'], n: 76 },
    { w: 'recently', p: ['recent','ly'], g: ['happening not long ago','in a way that is'], grade: 'easy', books: ['Jeeves Stories','The Count of Monte Cristo','Celtic Fairy Tales'], n: 33 },
    { w: 'recorded', p: ['record','ed'], g: ['to write down or save','past tense'], grade: 'easy', books: ['Frankenstein','Short Fiction','The Count of Monte Cristo'], n: 15 },
    { w: 'records', p: ['record','s'], g: ['written notes or saved data','plural / present tense'], grade: 'easy', books: ['The Adventures of Sherlock Holmes','Short Fiction','Dracula'], n: 16 },
    { w: 'refined', p: ['refin','ed'], lemma: ['refine','ed'], g: ['to purify or make fine','past tense'], grade: 'medium', books: ['Short Fiction','Jane Eyre','The Children of Odin: The Book of Northern Myths'], n: 16 },
    { w: 'remained', p: ['remain','ed'], g: ['to stay behind','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','White Fang','Frankenstein'], n: 69 },
    { w: 'remaining', p: ['remain','ing'], g: ['to stay behind','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','A Girl of the Limberlost','Pride and Prejudice'], n: 46 },
    { w: 'remains', p: ['remain','s'], g: ['to stay behind / leftover parts','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Journey to the Center of the Earth','Frankenstein'], n: 50 },
    { w: 'remembered', p: ['remember','ed'], g: ['to recall to mind','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Jeeves Stories'], n: 72 },
    { w: 'remembering', p: ['remember','ing'], g: ['to recall to mind','doing action'], grade: 'easy', books: ['Little Women','Daughters of the Dominion: A Story of the Canadian Frontier','The Count of Monte Cristo'], n: 49 },
    { w: 'remembers', p: ['remember','s'], g: ['to recall to mind','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','A Little Princess','English Fairy Tales'], n: 13 },
    { w: 'repaired', p: ['repair','ed'], g: ['to fix or mend','past tense'], grade: 'easy', books: ['Jane Eyre','Pride and Prejudice','Tom Swift and His Motor-Cycle'], n: 28 },
    { w: 'resented', p: ['resent','ed'], g: ['to feel hurt or angry about','past tense'], grade: 'medium', books: ['White Fang','Pride and Prejudice','Little Women'], n: 19 },
    { w: 'resentment', p: ['resent','ment'], g: ['to feel hurt or angry about','feeling or state of'], grade: 'medium', books: ['Pride and Prejudice','Northanger Abbey','Barry Locke, half-back'], n: 24 },
    { w: 'resigned', p: ['resign','ed'], g: ['to step down or accept','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Pride and Prejudice','Journey to the Center of the Earth'], n: 21 },
    { w: 'resumed', p: ['resum','ed'], lemma: ['resume','ed'], g: ['to start again','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Jane Eyre','Journey to the Center of the Earth'], n: 41 },
    { w: 'retreated', p: ['retreat','ed'], g: ['to move back or withdraw','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','The War of the Worlds'], n: 30 },
    { w: 'retreating', p: ['retreat','ing'], g: ['to move back or withdraw','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','White Fang','Daughters of the Dominion: A Story of the Canadian Frontier'], n: 18 },
    { w: 'rewarded', p: ['reward','ed'], g: ['to give a prize or pay','past tense'], grade: 'easy', books: ['English Fairy Tales','The Count of Monte Cristo','Pride and Prejudice'], n: 32 },
    { w: 'ungrateful', p: ['un','grateful'], g: ['not','thankful or appreciative'], grade: 'easy', books: ['The Count of Monte Cristo','The Adventures of Sherlock Holmes','The Phoenix and the Carpet'], n: 30 },
    { w: 'delightedly', p: ['delight','ed','ly'], g: ['great joy or pleasure','state of being','in a way that is'], grade: 'medium', books: ['The Box-Car Children','Rebecca of Sunnybrook Farm','Anne of Green Gables'], n: 13 },
    { w: 'departed', p: ['de','part','ed'], g: ['away / off','to leave or divide','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Frankenstein'], n: 49 },
    { w: 'department', p: ['de','part','ment'], g: ['away / separate','to section or divide','result or section'], grade: 'medium', books: ['Short Fiction','The Count of Monte Cristo','The Girls of Central High on Lake Luna'], n: 25 },
    { w: 'deportment', p: ['de','port','ment'], g: ['down / away','to carry oneself','behavior or manner'], grade: 'hard', books: ['The Girls of Central High','The Girls of Central High at Basketball','Little Women'], n: 13 },
    { w: 'depressed', p: ['de','press','ed'], g: ['down','to push','past tense / state of'], grade: 'easy', books: ['Jeeves Stories','Jane Eyre','The Wind in the Willows'], n: 29 },
    { w: 'depressing', p: ['de','press','ing'], g: ['down','to push','causing action'], grade: 'easy', books: ['Short Fiction','Daughters of the Dominion: A Story of the Canadian Frontier','At the Back of the North Wind'], n: 16 },
    { w: 'disagreeable', p: ['dis','agree','able'], g: ['not / opposite','to concur or match','able to be'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Northanger Abbey'], n: 39 },
    { w: 'disappeared', p: ['dis','appear','ed'], g: ['not / reverse','to come into sight','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Heidi','The Black Arrow: A Tale of the Two Roses'], n: 68 },
    { w: 'disappearing', p: ['dis','appear','ing'], g: ['not / reverse','to come into sight','doing action'], grade: 'easy', books: ['White Fang','The Count of Monte Cristo','Tom Sawyer Abroad'], n: 24 },
    { w: 'discontented', p: ['dis','content','ed'], g: ['not','satisfied or happy','state of being'], grade: 'medium', books: ['Little Women','Fables','The Story of the Amulet'], n: 12 },
    { w: 'discovered', p: ['dis','cover','ed'], g: ['remove / un-','to hide or overlay','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','Little Women'], n: 66 },
    { w: 'discovering', p: ['dis','cover','ing'], g: ['remove / un-','to hide or overlay','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Daughters of the Dominion: A Story of the Canadian Frontier','The Adventures of Sherlock Holmes'], n: 22 },
    { w: 'discovery', p: ['dis','cover','y'], g: ['remove / un-','to hide or overlay','action or result'], grade: 'easy', books: ['Frankenstein','The Count of Monte Cristo','Journey to the Center of the Earth'], n: 55 },
    { w: 'diseases', p: ['dis','ease','s'], g: ['lack of / away','comfort or health','plural'], grade: 'medium', books: ['Three Men in a Boat','Dracula','The Count of Monte Cristo'], n: 11 },
    { w: 'disgraceful', p: ['dis','grace','ful'], g: ['loss of / not','honor or favor','full of'], grade: 'easy', books: ['Pride and Prejudice','The Adventures of Pinocchio','Three Men in a Boat'], n: 16 },
    { w: 'dismissed', p: ['dis','miss','ed'], g: ['away','to send','past tense'], grade: 'easy', books: ['Jane Eyre','The Count of Monte Cristo','The High School Left End'], n: 40 },
    { w: 'dismounted', p: ['dis','mount','ed'], g: ['off / reverse','to get onto','past tense'], grade: 'easy', books: ['The Black Arrow: A Tale of the Two Roses','The Prisoner of Zenda','Short Fiction'], n: 15 },
    { w: 'disordered', p: ['dis','order','ed'], g: ['lack of / not','arrangement or rule','past tense / state of'], grade: 'easy', books: ['The Count of Monte Cristo','The War of the Worlds','Short Fiction'], n: 17 },
    { w: 'disrespectful', p: ['dis','respect','ful'], g: ['lack of / not','honor or courtesy','full of'], grade: 'easy', books: ['Daddy Long-Legs','The Prisoner of Zenda','At the Back of the North Wind'], n: 12 },
    { w: 'exacting', p: ['ex','act','ing'], g: ['out / thoroughly','to do or drive','doing action'], grade: 'medium', books: ['Jane Eyre','The Count of Monte Cristo','Ruth Fielding of the Red Mill'], n: 12 },
    { w: 'exactly', p: ['ex','act','ly'], g: ['out / thoroughly','to do or drive','in a way that is'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Short Fiction'], n: 70 },
    { w: 'exclaimed', p: ['ex','claim','ed'], g: ['out','to call or shout','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Outdoor Girls of Deepdale','Grace Harlowe\'s Plebe Year at High School / The Merry Doings of the Oakdale Freshmen Girls'], n: 66 },
    { w: 'exclaiming', p: ['ex','claim','ing'], g: ['out','to call or shout','doing action'], grade: 'easy', books: ['Little Women','The Count of Monte Cristo','Understood Betsy'], n: 17 },
    { w: 'explained', p: ['ex','plain','ed'], g: ['out','clear or simple','past tense'], grade: 'easy', books: ['Short Fiction','The Story of the Treasure Seekers','A Little Princess'], n: 64 },
    { w: 'explaining', p: ['ex','plain','ing'], g: ['out','clear or simple','doing action'], grade: 'easy', books: ['A Girl of the Limberlost','The Half-Back: A Story of School, Football, and Golf','The Half-Back: A Story of School, Football, and Golf'], n: 34 },
    { w: 'explains', p: ['ex','plain','s'], g: ['out','clear or simple','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Tom Sawyer Abroad','Short Fiction'], n: 14 },
    { w: 'expressed', p: ['ex','press','ed'], g: ['out','to push','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','Pride and Prejudice'], n: 50 },
    { w: 'expressing', p: ['ex','press','ing'], g: ['out','to push','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','White Fang'], n: 19 },
    { w: 'expressive', p: ['ex','press','ive'], g: ['out','to push','having the quality of'], grade: 'medium', books: ['The Count of Monte Cristo','Frankenstein','Little Women'], n: 17 },
    { w: 'expressly', p: ['ex','press','ly'], g: ['out','to push / clear','in a way that is'], grade: 'medium', books: ['The Count of Monte Cristo','The Magic City','Short Fiction'], n: 17 },
    { w: 'extended', p: ['ex','tend','ed'], g: ['out','to stretch','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','The War of the Worlds'], n: 43 },
    { w: 'extending', p: ['ex','tend','ing'], g: ['out','to stretch','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Jane Eyre'], n: 20 },
    { w: 'impatiently', p: ['im','patient','ly'], g: ['not','able to wait calmly','in a way that is'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','The Phoenix and the Carpet'], n: 45 },
    { w: 'impressed', p: ['im','press','ed'], g: ['in / upon','to push','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','Little Women'], n: 37 },
    { w: 'impressive', p: ['im','press','ive'], g: ['in / upon','to push','having the quality of'], grade: 'easy', books: ['The Prince and the Pauper','Jane Eyre','Rebecca of Sunnybrook Farm'], n: 19 },
    { w: 'imprisoned', p: ['im','prison','ed'], g: ['in / into','jail or place of confinement','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Indian Fairy Tales','The Magic City'], n: 20 },
    { w: 'imprisonment', p: ['im','prison','ment'], g: ['in / into','jail or place of confinement','state or act of'], grade: 'medium', books: ['The Count of Monte Cristo','The War of the Worlds','The Prince and the Pauper'], n: 16 },
    { w: 'impulses', p: ['im','pulse','s'], g: ['in / toward','drive or beat','plural'], grade: 'medium', books: ['White Fang','Jane Eyre','Frankenstein'], n: 13 },
    { w: 'indebted', p: ['in','debt','ed'], g: ['in','something owed','state of being'], grade: 'medium', books: ['The Count of Monte Cristo','Pride and Prejudice','The Adventures of Sherlock Holmes'], n: 12 },
    { w: 'indifferently', p: ['in','different','ly'], g: ['not','distinguishing or concerned','in a way that is'], grade: 'medium', books: ['Understood Betsy','The Ranch Girls at Rainbow Lodge','The Secret of the Old Clock'], n: 16 },
    { w: 'indoors', p: ['in','door','s'], g: ['inside','entryway or building','plural / adverbial'], grade: 'easy', books: ['Daughters of the Dominion: A Story of the Canadian Frontier','Five Children and It','The Wind in the Willows'], n: 25 },
    { w: 'inmates', p: ['in','mate','s'], g: ['inside','companion or resident','plural'], grade: 'medium', books: ['Jane Eyre','The Count of Monte Cristo','The Girls of Central High at Basketball'], n: 17 },
    { w: 'installed', p: ['in','stall','ed'], g: ['in / into','place or booth','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','The Girl from the Big Horn Country'], n: 16 },
    { w: 'intended', p: ['in','tend','ed'], g: ['towards / upon','to stretch or aim','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Short Fiction'], n: 62 },
    { w: 'intending', p: ['in','tend','ing'], g: ['towards / upon','to stretch or aim','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','The Adventures of Pinocchio'], n: 28 },
    { w: 'intends', p: ['in','tend','s'], g: ['towards / upon','to stretch or aim','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Grace Harlowe\'s Plebe Year at High School / The Merry Doings of the Oakdale Freshmen Girls'], n: 14 },
    { w: 'intensely', p: ['in','tense','ly'], g: ['in / upon','stretched or strong','in a way that is'], grade: 'medium', books: ['The War of the Worlds','Three Men in a Boat','The Count of Monte Cristo'], n: 24 },
    { w: 'inwardly', p: ['in','ward','ly'], g: ['inside','toward direction','in a way that is'], grade: 'easy', books: ['Jane Eyre','The Prince and the Pauper','A Girl of the Limberlost'], n: 18 },
    { w: 'misfortunes', p: ['mis','fortune','s'], g: ['bad / wrong','luck or chance','plural'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','The Adventures of Pinocchio'], n: 22 },
    { w: 'misgivings', p: ['mis','giving','s'], g: ['bad / wrong','yielding or feeling','plural'], grade: 'medium', books: ['The Prince and the Pauper','The Adventures of Sherlock Holmes','The Tower Treasure'], n: 13 },
    { w: 'mistakes', p: ['mis','take','s'], g: ['wrong / bad','to choose or hold','plural'], grade: 'easy', books: ['Anne of Green Gables','Little Women','The Count of Monte Cristo'], n: 25 },
    { w: 'outdoors', p: ['out','door','s'], g: ['outside','entryway or building','plural / adverbial'], grade: 'easy', books: ['Short Fiction','A Girl of the Limberlost','The Chums of Scranton High at Ice Hockey'], n: 16 },
    { w: 'outskirts', p: ['out','skirt','s'], g: ['outer','edge or border','plural'], grade: 'easy', books: ['The Black Arrow: A Tale of the Two Roses','The Tower Treasure','The Prisoner of Zenda'], n: 24 },
    { w: 'outstretched', p: ['out','stretch','ed'], g: ['out','to extend','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Journey to the Center of the Earth','The Half-Back: A Story of School, Football, and Golf'], n: 24 },
    { w: 'overflowed', p: ['over','flow','ed'], g: ['excess / above','to run like water','past tense'], grade: 'easy', books: ['Frankenstein','The Count of Monte Cristo','Jane Eyre'], n: 17 },
    { w: 'overflowing', p: ['over','flow','ing'], g: ['excess / above','to run like water','doing action'], grade: 'easy', books: ['Jane Eyre','A Girl of the Limberlost','Little Women'], n: 18 },
    { w: 'overhanging', p: ['over','hang','ing'], g: ['above','to suspend','doing action'], grade: 'easy', books: ['The Lost World','The Secret of the Old Clock','The Count of Monte Cristo'], n: 20 },
    { w: 'overjoyed', p: ['over','joy','ed'], g: ['excessive / very','happiness','state of being'], grade: 'easy', books: ['Heidi','English Fairy Tales','Fables'], n: 17 },
    { w: 'overlooked', p: ['over','look','ed'], g: ['above / beyond','to view','past tense'], grade: 'easy', books: ['Jeeves Stories','Short Fiction','The Count of Monte Cristo'], n: 28 },
    { w: 'overlooking', p: ['over','look','ing'], g: ['above / beyond','to view','doing action'], grade: 'easy', books: ['Jeeves Stories','The Count of Monte Cristo','The Girls of Central High at Basketball'], n: 18 },
    { w: 'overpowered', p: ['over','power','ed'], g: ['excessive / beyond','strength or control','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Pride and Prejudice'], n: 22 },
    { w: 'overpowering', p: ['over','power','ing'], g: ['excessive / beyond','strength or control','doing action'], grade: 'easy', books: ['The Lost World','The Adventures of Sherlock Holmes','The Count of Monte Cristo'], n: 18 },
    { w: 'overturned', p: ['over','turn','ed'], g: ['upside down / over','to rotate','past tense'], grade: 'easy', books: ['The War of the Worlds','White Fang','Short Fiction'], n: 17 },
    { w: 'precautions', p: ['pre','caution','s'], g: ['before','care or warning','plural'], grade: 'medium', books: ['The Count of Monte Cristo','Treasure Island','Jane Eyre'], n: 16 },
    { w: 'reappeared', p: ['re','appear','ed'], g: ['again','to come into sight','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Wind in the Willows','Jane Eyre'], n: 21 },
    { w: 'reassuringly', p: ['re','assuring','ly'], g: ['again','giving confidence','in a way that is'], grade: 'medium', books: ['Short Fiction','The Girl Aviators and the Phantom Airship','The Prisoner of Zenda'], n: 17 },
    { w: 'recalled', p: ['re','call','ed'], g: ['back / again','to summon or remember','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Anne of Green Gables'], n: 40 },
    { w: 'recalling', p: ['re','call','ing'], g: ['back / again','to summon or remember','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Peter and Wendy','Barry Locke, half-back'], n: 10 },
    { w: 'recoiled', p: ['re','coil','ed'], g: ['back','to spring or wind','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Dracula','White Fang'], n: 14 },
    { w: 'recollected', p: ['re','collect','ed'], g: ['again / back','to gather','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Pride and Prejudice','Northanger Abbey'], n: 20 },
    { w: 'recollections', p: ['re','collection','s'], g: ['back / again','gathering of memories','plural'], grade: 'medium', books: ['The Count of Monte Cristo','Jane Eyre','Pride and Prejudice'], n: 17 },
    { w: 'recovered', p: ['re','cover','ed'], g: ['back / again','to hide or find','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Frankenstein','The Adventures of Sherlock Holmes'], n: 58 },
    { w: 'recovering', p: ['re','cover','ing'], g: ['back / again','to hide or find','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','The Tower Treasure'], n: 29 },
    { w: 'recovery', p: ['re','cover','y'], g: ['back / again','to find or heal','act or state of'], grade: 'easy', books: ['Daughters of the Dominion: A Story of the Canadian Frontier','Pride and Prejudice','The Circular Staircase'], n: 27 },
    { w: 'refreshed', p: ['re','fresh','ed'], g: ['again','new or clean','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','At the Back of the North Wind'], n: 27 },
    { w: 'refreshing', p: ['re','fresh','ing'], g: ['again','new or clean','doing action'], grade: 'easy', books: ['Little Women','Jeeves Stories','The Count of Monte Cristo'], n: 15 },
    { w: 'refreshment', p: ['re','fresh','ment'], g: ['again','new or clean','thing or state'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Pride and Prejudice'], n: 19 },
    { w: 'regained', p: ['re','gain','ed'], g: ['again / back','to get or win','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','White Fang'], n: 25 },
    { w: 'rejoined', p: ['re','join','ed'], g: ['again / back','to unite or connect','past tense'], grade: 'easy', books: ['The Girl Aviators and the Phantom Airship','Pollyanna','The High School Left End'], n: 29 },
    { w: 'remarkable', p: ['re','mark','able'], g: ['again / thoroughly','to note or notice','worthy of / able to be'], grade: 'easy', books: ['The Adventures of Sherlock Holmes','The Count of Monte Cristo','Journey to the Center of the Earth'], n: 51 },
    { w: 'remarked', p: ['re','mark','ed'], g: ['again / thoroughly','to note or say','past tense'], grade: 'easy', books: ['The Adventures of Sherlock Holmes','Daughters of the Dominion: A Story of the Canadian Frontier','The Outdoor Girls of Deepdale'], n: 62 },
    { w: 'remarking', p: ['re','mark','ing'], g: ['again / thoroughly','to note or say','doing action'], grade: 'easy', books: ['The Wind in the Willows','The Count of Monte Cristo','Alice’s Adventures in Wonderland'], n: 14 },
    { w: 'remarks', p: ['re','mark','s'], g: ['again / thoroughly','to note or say','plural / present tense'], grade: 'easy', books: ['Indian Fairy Tales','Celtic Fairy Tales','English Fairy Tales'], n: 48 },
    { w: 'reminded', p: ['re','mind','ed'], g: ['again / back','memory or thought','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','Jane Eyre'], n: 50 },
    { w: 'reminding', p: ['re','mind','ing'], g: ['again / back','memory or thought','doing action'], grade: 'easy', books: ['The Story of the Amulet','The Lost World','Dracula'], n: 19 },
    { w: 'reminds', p: ['re','mind','s'], g: ['again / back','memory or thought','plural / present tense'], grade: 'easy', books: ['Jeeves Stories','The Count of Monte Cristo','Daughters of the Dominion: A Story of the Canadian Frontier'], n: 25 },
    { w: 'renewed', p: ['re','new','ed'], g: ['again','fresh or recent','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Pride and Prejudice'], n: 37 },
    { w: 'reported', p: ['re','port','ed'], g: ['back','to carry','past tense'], grade: 'easy', books: ['Dracula','The Circular Staircase','The Count of Monte Cristo'], n: 38 },
    { w: 'reporters', p: ['report','er','s'], g: ['to state or tell news','one who does','plural'], grade: 'easy', books: ['Short Fiction','The High School Left End','Jeeves Stories'], n: 8 },
    { w: 'reports', p: ['re','port','s'], g: ['back','to carry','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jeeves Stories','The Prisoner of Zenda'], n: 26 },
    { w: 'represented', p: ['re','present','ed'], g: ['again / on behalf of','to show or stand for','past tense'], grade: 'medium', books: ['Pride and Prejudice','The Count of Monte Cristo','Celtic Fairy Tales'], n: 26 },
    { w: 'representing', p: ['re','present','ing'], g: ['again / on behalf of','to show or stand for','doing action'], grade: 'medium', books: ['The Count of Monte Cristo','Rebecca of Sunnybrook Farm','Short Fiction'], n: 17 },
    { w: 'repressed', p: ['re','press','ed'], g: ['back','to push','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Jane Eyre','A Little Princess'], n: 12 },
    { w: 'requested', p: ['re','quest','ed'], g: ['again / thoroughly','to seek or ask','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','Jane Eyre','Indian Fairy Tales'], n: 24 },
    { w: 'resolutions', p: ['re','solution','s'], g: ['firmly / again','solving or decision','plural'], grade: 'medium', books: ['The Count of Monte Cristo','Little Women','Five Children and It'], n: 12 },
    { w: 'resounded', p: ['re','sound','ed'], g: ['back / again','noise or tone','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Heidi','Grace Harlowe\'s Plebe Year at High School / The Merry Doings of the Oakdale Freshmen Girls'], n: 11 },
    { w: 'resources', p: ['re','source','s'], g: ['again / back','origin or supply','plural'], grade: 'medium', books: ['The Count of Monte Cristo','The Lost World','Jane Eyre'], n: 14 },
    { w: 'restrained', p: ['re','strain','ed'], g: ['back','to pull tight or hold','past tense'], grade: 'medium', books: ['The Count of Monte Cristo','Little Women','Jane Eyre'], n: 27 },
    { w: 'returned', p: ['re','turn','ed'], g: ['back','to rotate or move','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Black Arrow: A Tale of the Two Roses','Little Women'], n: 76 },
    { w: 'returning', p: ['re','turn','ing'], g: ['back','to rotate or move','doing action'], grade: 'easy', books: ['The Count of Monte Cristo','The Adventures of Sherlock Holmes','Pride and Prejudice'], n: 61 },
    { w: 'returns', p: ['re','turn','s'], g: ['back','to rotate or move','plural / present tense'], grade: 'easy', books: ['A Girl of the Limberlost','The Count of Monte Cristo','Jane Eyre'], n: 23 },
    { w: 'transformed', p: ['trans','form','ed'], g: ['across / change','shape or outline','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Children of Odin: The Book of Northern Myths','Jane Eyre'], n: 21 },
    { w: 'transported', p: ['trans','port','ed'], g: ['across','to carry','past tense'], grade: 'easy', books: ['Frankenstein','The Count of Monte Cristo','Jane Eyre'], n: 14 },
    { w: 'unaccountable', p: ['un','account','able'], g: ['not','to explain or answer for','able to be'], grade: 'medium', books: ['Three Men in a Boat','White Fang','Northanger Abbey'], n: 17 },
    { w: 'unbearable', p: ['un','bear','able'], g: ['not','to stand or endure','able to be'], grade: 'easy', books: ['Journey to the Center of the Earth','A Little Princess','The Count of Monte Cristo'], n: 13 },
    { w: 'uncomfortable', p: ['un','comfort','able'], g: ['not','ease or relief','able to be'], grade: 'easy', books: ['Little Women','The Story of the Treasure Seekers','Northanger Abbey'], n: 57 },
    { w: 'uncommonly', p: ['un','common','ly'], g: ['not','usual or ordinary','in a way that is'], grade: 'medium', books: ['Pride and Prejudice','Little Women','The Prisoner of Zenda'], n: 14 },
    { w: 'unconsciously', p: ['un','conscious','ly'], g: ['not','aware or awake','in a way that is'], grade: 'medium', books: ['Little Women','The Count of Monte Cristo','Dracula'], n: 31 },
    { w: 'uncovered', p: ['un','cover','ed'], g: ['not / reverse','to hide or wrap','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Prisoner of Zenda','The Prince and the Pauper'], n: 26 },
    { w: 'understanding', p: ['under','stand','ing'], g: ['beneath / among','to hold position','state of being'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','Northanger Abbey'], n: 42 },
    { w: 'understands', p: ['under','stand','s'], g: ['beneath / among','to hold position','plural / present tense'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Black Beauty'], n: 20 },
    { w: 'undisturbed', p: ['un','disturb','ed'], g: ['not','to bother or trouble','past tense / state of'], grade: 'easy', books: ['The Girl from the Big Horn Country','The Circular Staircase','The Count of Monte Cristo'], n: 20 },
    { w: 'undoubtedly', p: ['un','doubted','ly'], g: ['not','questioned or uncertain','in a way that is'], grade: 'medium', books: ['The Count of Monte Cristo','Jeeves Stories','Pride and Prejudice'], n: 32 },
    { w: 'undressed', p: ['un','dress','ed'], g: ['reverse / take off','clothing','past tense'], grade: 'easy', books: ['Jeeves Stories','Jane Eyre','Understood Betsy'], n: 19 },
    { w: 'unearthly', p: ['un','earth','ly'], g: ['not','world or soil','having the nature of'], grade: 'medium', books: ['The Count of Monte Cristo','The War of the Worlds','Frankenstein'], n: 12 },
    { w: 'unexpected', p: ['un','expect','ed'], g: ['not','to look for or await','past tense / state of'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','Jane Eyre'], n: 50 },
    { w: 'unexpectedly', p: ['un','expected','ly'], g: ['not','looked for or awaited','in a way that is'], grade: 'medium', books: ['The Secret of the Old Clock','The Count of Monte Cristo','The Story of the Amulet'], n: 35 },
    { w: 'unfastened', p: ['un','fasten','ed'], g: ['reverse / undo','to attach or lock','past tense'], grade: 'easy', books: ['Daughters of the Dominion: A Story of the Canadian Frontier','The Call of the Wild','The Wind in the Willows'], n: 15 },
    { w: 'unfinished', p: ['un','finish','ed'], g: ['not','to complete or end','past tense / state of'], grade: 'easy', books: ['Little Women','Barry Locke, half-back','The Circular Staircase'], n: 16 },
    { w: 'unfolded', p: ['un','fold','ed'], g: ['not / reverse','to bend over','past tense'], grade: 'easy', books: ['Pride and Prejudice','Short Fiction','The Count of Monte Cristo'], n: 27 },
    { w: 'unfortunately', p: ['un','fortunate','ly'], g: ['not','lucky or favored','in a way that is'], grade: 'easy', books: ['The Count of Monte Cristo','Little Women','The Adventures of Pinocchio'], n: 35 },
    { w: 'unfriendly', p: ['un','friend','ly'], g: ['not','companion or pal','having the nature of'], grade: 'easy', books: ['Northanger Abbey','The Wind in the Willows','The Ranch Girls at Rainbow Lodge'], n: 17 },
    { w: 'uninteresting', p: ['un','interest','ing'], g: ['not','holding attention','having the quality of'], grade: 'easy', books: ['Three Men in a Boat','Little Women','The Story of the Amulet'], n: 12 },
    { w: 'unkindly', p: ['un','kind','ly'], g: ['not','caring or gentle','in a way that is'], grade: 'easy', books: ['Ruth Fielding of the Red Mill','Short Fiction','The Secret of the Old Clock'], n: 15 },
    { w: 'unlikely', p: ['un','like','ly'], g: ['not','similar or probable','having the nature of'], grade: 'easy', books: ['The Magic City','Pride and Prejudice','Celtic Fairy Tales'], n: 21 },
    { w: 'unlimited', p: ['un','limit','ed'], g: ['not','boundary or restriction','past tense / state of'], grade: 'easy', books: ['The Count of Monte Cristo','Short Fiction','Jane Eyre'], n: 12 },
    { w: 'unlocked', p: ['un','lock','ed'], g: ['reverse / undo','fastening or latch','past tense'], grade: 'easy', books: ['The Adventures of Sherlock Holmes','Dracula','A Girl of the Limberlost'], n: 29 },
    { w: 'unlucky', p: ['un','luck','y'], g: ['not','chance or fortune','having the quality of'], grade: 'easy', books: ['Pride and Prejudice','Anne of Green Gables','The Story of the Treasure Seekers'], n: 27 },
    { w: 'unpacked', p: ['un','pack','ed'], g: ['reverse / undo','to bundle or store','past tense'], grade: 'easy', books: ['Daddy Long-Legs','The Story of the Treasure Seekers','The Adventures of Sherlock Holmes'], n: 18 },
    { w: 'unreasonable', p: ['un','reason','able'], g: ['not','logic or sense','able to be'], grade: 'easy', books: ['Pride and Prejudice','The Magic City','Daddy Long-Legs'], n: 17 },
    { w: 'unselfish', p: ['un','self','ish'], g: ['not','one\'s own person','concerned with'], grade: 'easy', books: ['Dracula','Little Women','The Story of the Amulet'], n: 13 },
    { w: 'unspeakable', p: ['un','speak','able'], g: ['not','to say or utter','able to be'], grade: 'medium', books: ['Journey to the Center of the Earth','Dracula','Little Women'], n: 15 },
    { w: 'unsteady', p: ['un','stead','y'], g: ['not','firm place or standing','having the quality of'], grade: 'easy', books: ['Daughters of the Dominion: A Story of the Canadian Frontier','Black Beauty','The Secret of the Old Clock'], n: 19 },
    { w: 'unsuccessful', p: ['un','success','ful'], g: ['not','achievement or win','full of'], grade: 'easy', books: ['The Count of Monte Cristo','The Secret of the Old Clock','The Tower Treasure'], n: 17 },
    { w: 'untouched', p: ['un','touch','ed'], g: ['not','to feel or reach','past tense'], grade: 'easy', books: ['The Count of Monte Cristo','The Secret of the Old Clock','The Box-Car Children'], n: 20 },
    { w: 'unusually', p: ['un','usual','ly'], g: ['not','common or normal','in a way that is'], grade: 'easy', books: ['Little Women','Toby Tyler','White Fang'], n: 30 },
    { w: 'unwilling', p: ['un','will','ing'], g: ['not','desire or choice','having the quality of'], grade: 'easy', books: ['The Count of Monte Cristo','Pride and Prejudice','The Prisoner of Zenda'], n: 18 },
    { w: 'unwillingly', p: ['un','willing','ly'], g: ['not','ready or inclined','in a way that is'], grade: 'medium', books: ['Pride and Prejudice','Barry Locke, half-back','The Secret of the Old Clock'], n: 19 },
    { w: 'unworthy', p: ['un','worth','y'], g: ['not','value or merit','having the quality of'], grade: 'easy', books: ['The Count of Monte Cristo','Northanger Abbey','Pride and Prejudice'], n: 25 },
];

export const BY_PARTS = {
    2: SHATTER_WORDS.filter(e => e.p.length === 2),
    3: SHATTER_WORDS.filter(e => e.p.length === 3),
    4: SHATTER_WORDS.filter(e => e.p.length === 4),
};

